[development]
address = "localhost"
port = 9999
workers = 4
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
secret_key = "randomly generated at launch"
limits = { forms = 32768 }

[staging]
address = "localhost"
port = 9090
workers = 4
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
secret_key = "randomly generated at launch"
limits = { forms = 32768 }

[production]
address = "localhost"
port = 9999
workers = 4
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "critical"
secret_key = "randomly generated at launch"
limits = { forms = 32768 }